name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Docker image
        run: make build

      - name: Start services
        run: make up

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run linter
        run: make lint

      - name: Run tests
        run: make tests

      - name: Stop services
        run: make down
